# @package _global_

cdsb: False

# data 
Dataset: afhq_wild
data:
  dataset: afhq_wild_cat
  image_size: 512
  channels: 3

# transfer
transfer: True
Dataset_transfer: afhq_cat


final_adaptive: False
adaptive_mean: False
mean_final: torch.zeros([${data.channels}, ${data.image_size}, ${data.image_size}])
var_final: 1 * torch.ones([${data.channels}, ${data.image_size}, ${data.image_size}])

# device
device: cuda
num_workers: 4
pin_memory: True

# logging
log_stride: 100
gif_stride: 5000
plot_npar: 4
test_npar: 100
test_batch_size: 4
cache_npar: 400
cache_batch_size: 10
num_repeat_data: 1
cache_refresh_stride: 1000

# training
use_prev_net: True
ema: True
ema_rate: 0.999
grad_clipping: True
grad_clip: 1.0
batch_size: 4
num_iter: 25000
n_ipf: 30
lr: 0.0001

num_steps: 100
